# # Build settings
# markdown: kramdown
# theme: cayman

title: "Title"
description: "Description"

search_enabled: true
heading_anchors: true
color_scheme: dark
ga_tracking: UA-158921873-1

# Aux links for the upper right navigation

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
